---
- hosts: genki*
- vars_files:
    - "group_vars/vars.yml"
pre_tasks:
    - name: update apt cache if needed.
       apt: update_cache=yes cache_valid_time=3600
tasks:
    - name: 安装用于管理apt源工具
       apt: name={{item}} state=present
       with_items:
          - python-apt
          - python-pycurl
    - name: 添加php的ondrej源
       apt_repository: repo='ppa:ondrej/php' update_cache=yes
    - name: 安装 nginx,mysql,php 以及依赖
       apt: name={{ item }} state=present
        with_items:
          - git
          - curl
          - sendmail
          - nginx
          - php7.0
          - php7.0-common
          - php7.0-fpm
          - php7.0-mysql
          - php7.0-cli
          - php7.0-curl
          - php7.0-gd
          - php7.0-dev
          - php7.0-mcrypt
          - php-apcu
          - php-pear
          - python-mysqldb
          - mysql-server
    - name: "stop ufw"
       service: name=ufw state=stopped
    - name: start nginx,mysql,php
       service: "name={{ item }} state=started enabled=yes"
        with_items:
         - nginx
         - mysql
         - php7.0-fpm
    - name : 在nginx 中为Drupal 添加 virtualhost
       template:
         src: "templates/drupal.dev.conf.j2"
         dest: "/etc/nginx/sites-available/{{ domain }}.dev.conf"
         owner: root
         group: root
         mode: 0744
       notify: restart nginx
    - name: "配置php"
       template:
         src: "templates/php.j2"
         dest: "/etc/php/5.6/fpm/pool.d/www.conf"
       notify: restart php7.0-fpm
    - name: "Download composer installer"
       get_url:
         url: "https://getcomposer.org/installer"
         dest: /tmp/composer-installer.php
         mode: 0755
    - name: run composer installer
       command: >
         php composer-installer.php
         chdir=/tmp
         creates=/usr/local/bin/composer
    - name: move composer into globally-accessible location.
       shell: >
         mv /tmp/composer.phar /usr/local/bin/composer
         creates=/usr/local/bin/composer
handlers:
    - name: restart nginx
       service: name=nginx state=restarted
    - name: restart php7.0-fpm
       service: name=php7.0-fpm state=restarted

