---
- hosts: genki*
#pre_tasks:
#    - name: update apt cache if needed.
#       apt: update_cache=yes cache_valid_time=3600
tasks:
    - name: 安装用于管理apt源工具
       apt: name={{item}} state=present
       with_items:
          - python-apt
          - python-pycurl
    - name: 添加php的ondrej源
       apt_repository: repo='ppa:ondrej/php' update_cache=yes
    - name: 安装 nginx,mysql,php 以及依赖
       apt: name={{ item }} state=present
        with_items:
          - git
          - curl
          - sendmail
          - nginx
          - php7.0
          - php7.0-common
          - php7.0-fpm
          - php7.0-mysql
          - php7.0-cli
          - php7.0-curl
          - php7.0-gd
          - php7.0-dev
          - php7.0-mcrypt
          - php-apcu
          - php-pear
          - python-mysqldb
          - mysql-server
    - name: "stop ufw"
       service: name=ufw state=stopped
    - name: start nginx,mysql,php
       service: "name={{ item }} state=started enabled=yes"
        with_items:
         - nginx
         - mysql
         - php7.0-fpm
    - name : 在nginx 中为Drupal 添加 virtualhost
       template:
         src: "templates/drupal.dev.conf.j2"
         dest: "/etc/nginx/sites-available/{{ domain }}.dev.conf"
         owner: root
         group: root
         mode: 0744
       notify: restart nginx
    - name: "配置php"
       template:
         src: "templates/php.j2"
         dest: "/etc/php/7.0/fpm/pool.d/www.conf"
       notify: restart php7.0-fpm
    - name: "Download composer installer"
       get_url:
         url: "https://getcomposer.org/installer"
         dest: /tmp/composer-installer.php
         mode: 0755
    - name: run composer installer
       command: >
         php composer-installer.php
         chdir=/tmp
         creates=/usr/local/bin/composer
    - name: move composer into globally-accessible location.
       shell: >
         mv /tmp/composer.phar /usr/local/bin/composer
         creates=/usr/local/bin/composer
    - name: pull Drush code from github
       git:
         repo: https://github.com/drush-ops/drush.git
         dest: /opt/drush
    - name: 使用composer安装Drush
       shell: >
         /usr/local/bin/composer install
         chdir=/opt/drush
         creates=/opt/drush/vendor/autoload.php
    - name: 创建Drush命令符号链接
       file:
         src: /opt/drush/drush
         dest: /usr/local/bin/drush
         state: link
    - name: 下载Drupal代码到html目录
       git:
         repo: http://drupalcode.org/project/drupal.git
         version: "{{ drupal_core_version }}"
         dest: "{{ drupal_core_path }}"
    - name: install Drupal
       commond: >
         drush si -y --site-name="{{ drupal_site_name }}" --account-name=admin   --account-pass=admin --db-url=mysql://root@localhost/{{ domain }}
         chdir={{ drupal_core_path }}
         creates={{ drupal_core_path }}/sites/default/settings.php
       notify: restart nginx
    - name: 为settings.php设置正确权限
       file:
         path: "{{ drupal_core_path }}/sites/default/settings.php"
         mode: 0744
    - name: 开放file目录的所有权限
       file:
         path: "{{ drupal_core_path }}/sites/default/files"
         mode: 077
         state: directory
         recurse: yes
handlers:
    - name: restart nginx
       service: name=nginx state=restarted
    - name: restart php7.0-fpm
       service: name=php7.0-fpm state=restarted

